# Generated by Django 5.2 on 2025-05-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_movimientoinsumo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del insumo (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Valor unitario en CLP', max_digits=10),
        ),
    ]
