# Generated by Django 5.2 on 2025-05-19 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        ('pacientes', '0002_paciente_direccion_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoProductoEnFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_usados', to='pacientes.fichaclinica')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Uso de producto en ficha',
                'verbose_name_plural': 'Usos de productos en fichas',
            },
        ),
    ]
