# Generated by Django 5.2 on 2025-05-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='reservada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('general', 'Podología general'), ('reflexologia', 'Reflexología Podal'), ('hongos', 'Uñas con hongos (Onicomicosis)'), ('encarnada', 'Uña encarnada (Onicocriptosis)'), ('curacion', 'Curación Podología'), ('esmalte', 'Retiro de esmalte')], max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
