# Generated by Django 5.2 on 2025-05-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='duracion_minutos',
            field=models.IntegerField(default=60),
        ),
    ]
