# Generated by Django 5.2 on 2025-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_tratamiento_duracion_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('podologia', 'Podología'), ('manicura', 'Manicura')], default='podologia', max_length=20),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(choices=[('general', 'Podología general'), ('helomas', 'Helomas interdigitales'), ('hongos', 'Uñas con hongos (Onicomicosis)'), ('encarnada', 'Uña encarnada (Onicocriptosis)'), ('curacion', 'Curación Podología'), ('dermatomicoticos', 'Dermatomicoticos'), ('postura', 'Postura de brackets')], max_length=100),
        ),
    ]
