# Generated by Django 5.2 on 2025-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_tipo_cita_alter_tratamiento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(choices=[('general', 'Podología general'), ('helomas', 'Helomas interdigitales'), ('hongos', 'Uñas con hongos (Onicomicosis)'), ('encarnada', 'Uña encarnada (Onicocriptosis)'), ('curacion', 'Curación Podología'), ('dermatomicoticos', 'Dermatomicoticos'), ('postura', 'Postura de brackets'), ('manicura', 'Manicura')], max_length=100),
        ),
    ]
