# Generated by Django 5.2 on 2025-05-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_tratamiento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_extendida',
            field=models.BooleanField(default=False),
        ),
    ]
