# Generated by Django 5.2 on 2025-05-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_duracion_extendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_cita',
            field=models.IntegerField(choices=[(60, '1 hora'), (120, '2 horas')], default=60),
        ),
    ]
