# Generated by Django 4.2.11 on 2025-06-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_duracion_cita'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('fecha', 'hora', 'tipo_cita')},
        ),
    ]
